# Summary
- Create array
- Generative arrays using functions: </br>
    1.linspace </br>
    2.arange </br>
    3.ones </br>
    4.zeros </br>
    5.random.rand </br>
    6.logspace </br>
- Advantages of numpy
- Reshape an array
- Numpy operations
- Accessing Components
- Subset of arrays
- Modifying array

# Numerical Python (Numpy)

In [1]:
import numpy as np

## 1. Create an Array

In [2]:
x = np.array([4,5,6,7,8])
print(type(x))

<class 'numpy.ndarray'>


In [3]:
print(x)

[4 5 6 7 8]


### Generating Arrays using linspace()

In [4]:
# return step False
b=np.linspace(start=2, stop=6, num=10, endpoint=True, retstep=False)
print(b)

[2.         2.44444444 2.88888889 3.33333333 3.77777778 4.22222222
 4.66666667 5.11111111 5.55555556 6.        ]


In [5]:
# return step True
c=np.linspace(start=2, stop=6, num=10, endpoint=True, retstep=True)
print(c)

(array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ]), 0.4444444444444444)


### Generating arrays using arange()

In [6]:
d=np.arange(1,10,2)
print(d)

[1 3 5 7 9]


### Generate Arrays using Ones()

In [10]:
e=np.ones((4,5), str) # default data type: Float
print(e)

[['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']]


### Generate Arrays using zeros

In [ ]:
f=np.zeros((4,5))
print(f)

### Generating Arrays using random.rand()

In [11]:
g=np.random.rand(5)
print(g)

[0.59344082 0.42421992 0.79174737 0.75463796 0.17702076]


In [12]:
h=np.random.rand(3,3) # with prefered shape
print(h)

[[0.32378775 0.05073816 0.84300642]
 [0.52639805 0.90855922 0.86573605]
 [0.25928863 0.74773843 0.85155317]]


### Generate arrays using logspace()

In [13]:
i=np.logspace(1, 10, num=5, endpoint=True, base=10.0)
print(i)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


### Advantage of Numpy-Speed

In [14]:
j=range(1000)
print(j)

range(0, 1000)


In [15]:
timeit sum(j)

7.14 µs ± 809 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [16]:
k=np.array(j)

In [17]:
timeit sum(k)

36.9 µs ± 5.94 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### Advantage of numpy- storage space

In [18]:
import sys

In [19]:
w=[1, 2, 3, 4]

In [20]:
sys.getsizeof(1)*len(w)

112

In [21]:
b.itemsize * b.size

80

## Reshaping an array

In [29]:
grid= np.arange(start=1, stop=10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Array dimensions

## Create an array

In [37]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(a)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
b= np.arange(11,20).reshape(3,3)
print(b)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


## numpy Addition

In [35]:
add = np.add(a,b)
print(add)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


## numpy multipliction

In [39]:
mul = np.multiply(a,b)
print(mul)

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


## numpy Subtract

In [41]:
sub = np.subtract(a,b)
print(sub)

[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


## numpy Divide

In [43]:
div = np.divide(a,b)
print(div)

[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]


## numpy remainder

In [45]:
rem = np.remainder(a,b)
print(rem)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Accessing components of an array

In [48]:
print(b)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [51]:
b[1,1]

15

In [52]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
a[1:3] # Extract elements from second and third row of array 

array([[4, 5, 6],
       [7, 8, 9]])

In [59]:
a[:,0] # Extract elements from first columnb of array a

array([1, 4, 7])

In [64]:
a[0,:] # extract elements the first row of array

array([1])

## Subset of arrays

In [65]:
print(b)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [81]:
b_sub=b[1:3,1:3]
print(b_sub)

[[15 16]
 [18 19]]


In [82]:
b_sub[1,1]= 20

In [83]:
print(b_sub)

[[15 16]
 [18 20]]


## Modifying Array using append()

In [85]:
col = np.array([21, 22, 23]).reshape(3,1)
print(col)

[[21]
 [22]
 [23]]


In [88]:
a_col = np.append(a, col, axis=1)
print(a_col)

[[ 1  2  3 21]
 [ 4  5  6 22]
 [ 7  8  9 23]]


# Modify array using insert()

In [92]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [93]:
print(b)

[[11 12 13]
 [14 15 16]
 [17 18 20]]


In [94]:
a_ins = np.insert(a, 3, b[1:3], axis=0)

In [95]:
print(a_ins)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [14 15 16]
 [17 18 20]]


# Modifying array using delete()

In [102]:
a_del=np.delete(a_ins, 4, axis=0)

In [103]:
print(a_del)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [14 15 16]]


# --- END ---