## NumPy

NumPy is a python package and it stands for numerical python.\
Fundamental package for numerical computations in python.\
Supports N-dimensional array objects that can be used for processing mutidimentional data\
Supports different data-types

## Array

An array is a data structure that stores values of same data type.\
Lists can contain values corresponding to different data types.\
Arrays in python can only contain values corresponding to same data type

## NumPy Array

A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. \
the number of columns is the rank of the array.\
The shape of an array is a tuple of integers giving the size of the array along each dimension.

## Creation of array

In [5]:
my_list = [1, 2, 3, 4, 5, 6]
print(my_list)

[1, 2, 3, 4, 5, 6]


##### To create numpy array, we first need to import the numpy package
pip install numpy

In [3]:
import numpy as np

In [7]:
array = np.array(my_list, dtype = int)
print(array)

[1 2 3 4 5 6]


In [13]:
print(type(array))
print(len(array))
print(array.ndim)
print(array.shape)

<class 'numpy.ndarray'>
6
1
(6,)


In [14]:
array2 = array.reshape(3, 2) # reshape(rows, columns)
print(array2)
array2.shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [16]:
array3 = array.reshape(3, -1)
print(array3)
print(array3.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [18]:
## Initializing numpy arrays from nested python lists

my_list2 = [ 1, 2, 3, 4, 5 ]
my_list3 = [ 2, 3, 4, 5, 6 ]
my_list4 = [ 9, 7, 6, 8, 9 ]

mul_arr = np.array([my_list2, my_list3, my_list4])
print(mul_arr)

print(mul_arr.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
(3, 5)


In [19]:
mul_arr.reshape(1,15)


array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [ ]:
## NumPy-Atrributes

In [20]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [21]:
# reshaping the ndarray
a.shape = (3,2)     # different way
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
# Reshaping function to resize an array
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [23]:
r = range(24)

In [24]:
print(r)

range(0, 24)


In [25]:
# an array of evenly spaced numbers
a = np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [26]:
# Reshaping the array 'a'
b = a.reshape(6, 4, 1)    # (no of vectors, rows, columns)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


### numpy.add() - performs elementwise addition between two arrays
Syntax: numpy.add(array_1,array_2)

In [36]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x+y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


### numpy.subtract() - performs elementwise substraction between two arrays
Syntax: numpy.subract(array_1,array_2)

In [38]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


### numpy.multiply() - performs elementwise multiplication between two arrays
Syntax: numpy.multiply(array_1,array_2)

In [40]:
print(x * y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [42]:
print(x.dot(y))
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [44]:
print(x / y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### numpy.sum() - returns sum of all array elements or sum of all array elements over a given axis
Syntax: numpy.sum(array.axis)

In [45]:
print(np.sum(x))        # compute overall sum (axis-none)

10.0


In [46]:
print(np.sum(x, axis=0))    # compute sum of each column

[4. 6.]


In [47]:
print(np.sum(x, axis=1))    # compute sum of each row

[3. 7.]


In [4]:
x = np.array([1, -1, 2])
y = np.array([2, 5, 2])

In [5]:
print(x+y)

[3 4 4]


In [6]:
print(x-y)

[-1 -6  0]


In [8]:
#scalar mult:
print(3*x)

[ 3 -3  6]


In [10]:
print(np.linalg.norm(x))  #length

2.449489742783178


In [11]:
s=np.dot(x,y)
print(s)

1
